// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qstqklpjdwptskscqxle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzdHFrbHBqZHdwdHNrc2NxeGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDg5ODQsImV4cCI6MjA2ODAyNDk4NH0.mfmXZ3qHkjOcGhOfJTlXL1XA0PrPVgQ-rKyVBnsHttA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});